package com.ibm.ws.wlp.docgen.dita;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.stream.FactoryConfigurationError;
import javax.xml.stream.XMLStreamException;

public class DitaMapWriter {

  private XMLWriter writer;
  private String mapKind;
  private Map<String, Tagging> featureTagging = new HashMap<String, Tagging>();

  public DitaMapWriter(File ditaDir, String kind, String kindLabel, String edition, String lang, List<Tagging> featureTags) throws XMLStreamException, FactoryConfigurationError, IOException {
    mapKind = kind;
    File f = getDitaMap(ditaDir, mapKind, edition);
    writer = new XMLWriter(f);
    
    for (Tagging t : featureTags) {
      featureTagging.put(t.getName(), t);
    }

    writer.writeComment("Arbortext, Inc., 1988-2011, v.4002");
    writer.setDTD("<!DOCTYPE map PUBLIC \"-//IBM//DTD DITA IBM Map//EN\" \"../dtd/ibm-map.dtd\">");
    writer.writeProcessingInstruction("Pub Sty _display FontColor=\"red\"");
    writer.writeProcessingInstruction("Pub Inc");
    writer.pushElement("map");
    writer.addAttribute("xml:lang", lang);
    writer.pushElement("title");
    writer.addText("Liberty " + kindLabel);
    writer.pop("title"); // title
  }

  public static File getDitaMap(File ditaDir, String mapKind, String edition) {
    return new File(ditaDir, "wlp_" + mapKind + "s_" + edition + "_autogenerated.ditamap");
  }
  
  public void close() throws XMLStreamException, IOException {
    writer.pop("map");
    writer.writeProcessingInstruction("Pub Caret -1");
    writer.writeProcessingInstruction("Pub *0000000465");
    writer.close();
  }

  public void addEntry(String name, String displayName) throws XMLStreamException, IOException {
    writer.pushElement("topicref");
    Tagging t = featureTagging.get(name);
    if (t != null) {
      Map<String, String> tags = t.getTags();
      for (Map.Entry<String, String> entry : tags.entrySet()) {
        writer.addAttribute(entry.getKey(), entry.getValue());
      }
    }
    writer.addAttribute("href", "ae/rwlp_" + mapKind + "_" + name + ".dita");
    writer.addAttribute("navtitle", displayName);
    writer.addAttribute("locktitle", "yes");
    writer.pop("topicref");
  }

}
