package com.ibm.ws.wlp.docgen.dita;

import java.io.File;
import java.io.IOException;
import java.text.MessageFormat;
import java.util.Map;

import javax.xml.stream.FactoryConfigurationError;
import javax.xml.stream.XMLStreamException;

public class EntitiesDITAWriter {
  private XMLWriter writer;
  private Map<String, String> entityStrings;

  public EntitiesDITAWriter(File dir, Map<String, String> strings) throws XMLStreamException, FactoryConfigurationError, IOException {
    entityStrings = strings;
    
    if (!!!dir.exists()) {
      dir.mkdirs();
    }
    
    File f = new File(dir, "wlp_feature_entities_autogenerated.dita");
    writer = new XMLWriter(f);

    writer.writeComment("Arbortext, Inc., 1988-2011, v.4002");
    writer.setDTD("<!DOCTYPE topic PUBLIC \"-//IBM//DTD DITA IBM Topic//EN\" \"ibm-reference.dtd\">");
    writer.writeProcessingInstruction("Pub Sty _display FontColor=\"red\"");
    writer.writeProcessingInstruction("Pub Inc");
    writer.pushElement("topic");
    writer.addAttribute("id", "wlp_feature_entities_autogenerated");
    writer.addAttribute("xml:lang", "en-us");
    writer.pushElement("title");
    writer.addText("Feature entities");
    writer.pop("title");
    writer.writeProcessingInstruction("Pub Caret -2");
    writer.pushElement("body");
    writer.pushElement("section");
    writer.pushElement("title");
    writer.addText("Feature-specific phrases");
    writer.pop("title");
    writer.pushElement("lines");
  }

  public void addFeatureEntities(String featureId, String name) throws XMLStreamException, IOException {
    writer.addText("\r\n");
    writer.writeComment(featureId + " phrases");
    
    for (Map.Entry<String, String> entity : entityStrings.entrySet()) {
      String key = entity.getKey();
      if ("javaeeClient-7.0".equals(featureId) && !!!key.contains("_client")) {
    	  continue;
      }
      if (!!!"javaeeClient-7.0".equals(featureId) && key.contains("_client")) {
    	  continue;
      }
      writer.pushElement("ph");
      writer.addAttribute("id", key + "_" + featureId);
      String value = entity.getValue();
      value = MessageFormat.format(value, name);
      
      int index = value.indexOf("<filepath>");
      
      if (index == -1) {
        writer.addText(value);
      } else {
        int end;
        do {
          writer.addText(value.substring(0, index));
          writer.pushElement("filepath");
          index += 10;
          end = value.indexOf("</filepath>", index);
          
          writer.addText(value.substring(index, end));
          writer.pop("filepath");
          index = end + 11;
          end = value.indexOf("<filepath>", index);
        } while (end != -1);
        
        writer.addText(value.substring(index));
        
      }
      
      writer.pop("ph"); // ph
    }
  }
  
  public void close() {
    writer.close();
  }
}
